# Aruba population trends, 2015-2023


Source file: 1.11  Domiciliation by country of birth and sex (Aruba)\
Source: CBS Aruba and the Population Registry Office

---
## 1. Setup

## Imports and paths

This block of code is necessary to create a reproducible notebook environment.

In [1]:
# Importing necessary libraries

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

%matplotlib inline

import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()))

from config.project_paths import (
    ROOT,
    DATA_RAW,
    FIGURES
)

In [2]:
# Verify all paths to ensure stable environment

print("ROOT:", ROOT)
print("RAW DATA:", DATA_RAW)
print("FIGURES:", FIGURES)

ROOT: /home/ggirelli/Documents/DataAnalysis/projects/cbs_aruba
RAW DATA: /home/ggirelli/Documents/DataAnalysis/projects/cbs_aruba/data/raw
FIGURES: /home/ggirelli/Documents/DataAnalysis/projects/cbs_aruba/outputs/figures

In [3]:
DOMICIL_COUNTRY_SEX = DATA_RAW / "Table-1.11-Domiciliation-by-country-of-birth-and-sex.xlsx"

In [4]:
# # Stop early if the source file is missing

if not DOMICIL_COUNTRY_SEX.exists():
    raise FileNotFoundError

## 2. Load and inspect source table

In [5]:
raw_df = pd.read_excel(DOMICIL_COUNTRY_SEX, skiprows=1, header=None)

In [6]:
raw_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,NaN,2015,NaN,2016,NaN,2017,NaN,2018,NaN,2019,NaN,2020,NaN,2021,NaN,2022,NaN,2023,NaN
1,Country,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female
2,Total Domiciliation:,1780,1815,1264,1327,1291,1422,1420,1749,1312,1497,882,964,1015,1178,1174,1406,1455,1677
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aruba/ Neth. Ant.,432,420,415,389,429,416,424,407,382,345,338,295,362,322,344,344,368,382

In [7]:
# Remove empty row by splitting up data frame and concatenating it back

upper_df = raw_df.iloc[:3,:]
lower_df = raw_df.iloc[5:10,:]

main_df = pd.concat([upper_df, lower_df], axis=0, ignore_index=True).copy()

In [8]:
# Assign the name 'indicator' to the NULL value index 0:0

main_df.iloc[0,0]="indicator"

In [9]:
# Ffill year values

body_df = main_df.iloc[:,1:].ffill(axis=1)

In [10]:
# Isolate row names

main_df = main_df.iloc[:,0]

In [11]:
# Create a cleaned data frame

cleaned_df = pd.concat([main_df, body_df], axis=1)

In [12]:
# Promote first row to header

cleaned_df.columns = cleaned_df.iloc[0]
cleaned_df = cleaned_df.iloc[1:].reset_index(drop=True)

In [15]:
cleaned_df

,indicator,2015,2015,2016,2016,2017,2017,2018,2018,2019,2019,2020,2020,2021,2021,2022,2022,2023,2023
0,Country,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female,Male,Female
1,Total Domiciliation:,1780,1815,1264,1327,1291,1422,1420,1749,1312,1497,882,964,1015,1178,1174,1406,1455,1677
2,The Netherlands,370,335,284,303,294,295,257,303,231,216,186,201,186,211,239,208,255,265
3,Colombia,211,290,112,166,137,187,128,236,155,180,82,111,87,177,110,233,208,274
4,Venezuela,167,191,112,114,135,163,253,381,246,371,111,175,138,214,208,296,261,363
5,Dominican Republic,184,181,85,100,66,95,60,101,60,72,30,44,39,46,27,69,69,71
6,Other,416,398,256,255,230,266,298,321,238,313,135,138,203,208,246,256,294,322